---
- name: Install Nginx in AWS AMI Docker container
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install Docker Python package
      pip:
        name: docker
        state: present
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: yes

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx
      become: yes

    - name: Run Nginx Docker container
      docker_container:
        name: my-nginx
        image: nginx
        state: started
        ports:
          - "80:80"
      become: yes
