---
- name: Install Nginx in AWS AMI Docker container
  hosts: all
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: /home/arshak/Desktop/pem/virginia.pem
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  tasks:
    - name: Add NGINX conf
      file:
        src: /etc/nginx/sites-enabled/nginx.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
