---
- name: Install Nginx in AWS AMI Docker container
  hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "./../../../pem/virginia.pem"
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
    ansible_become: true
    ansible_become_user: root
  tasks:
    # - name: sleepy
    #   shell: ". /home/ubuntu/opt/scrap.sh > /dev/null 2>&1 &"
    - name: sleepy
      # shell: . /home/ubuntu/opt/scrap.sh > /dev/null 2>&1 &
      shell: . /home/ubuntu/opt/scrap.sh >/dev/null 2>&1 &
      async: 0
      poll: 0
