name: Test Node App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find index.json
        id: find-file
        run: |
          echo "::set-output name=file_path::$(find . -name 'index.json' -type f -print -quit)"

      - name: Run Packer build
        run: |
          packer build ${{ steps.find-file.outputs.file_path }}
