name: Test Node App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        # run: npm install
        run: |
          echo "AWS_ACCESS_KEY_ID=AKIA2SK7BR33VSVRFINF" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=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" >> $GITHUB_ENV

      - name: Run Packer build
        run: |
          packer build /packer/index.json